### Basic GET
GET http://localhost:80/echo

### Echo request through Gildra
GET http://localhost:80/echo?hey=ho

### Echo request through Gildra with replay (stay under)
GET http://localhost:80/echo?hey=ho&replay_lim=2

### Echo request through Gildra with replay (exceed)
GET http://localhost:80/echo?hey=ho&replay_lim=3