### Basic GET
GET http://localhost/echo

### Echo request through Gildra
GET http://localhost/echo?hey=ho

### Echo request through Gildra with replay (stay under)
GET http://localhost/echo?hey=ho&replay_lim=2

### Echo request through Gildra with replay (exceed)
GET http://localhost/echo?hey=ho&replay_lim=3

### Fail glob path matching
GET http://localhost/notecho